domain: imcodist.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://imcodist.github.io  # the base hostname and protocol for your site, e.g. http://example.com

title: "codist" # the name of your site, e.g. ACME Corp.

exclude:
- README.md

permalink: pretty

collections:
  projects:
    output: true

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    navurl: "/blog/"
    navtitle: "blog"

- scope:
    path: ""
    type: "projects"
  values:
    in_content: false
    layout: "project"
    navurl: "/projects/"
    navtitle: "projects"

- scope:
    path: ""
  values:
    layout: "default"